sonar.projectKey=PropGest
sonar.organization=jc2502
sonar.host.url=https://sonarcloud.io

sonar.sources=backend/src,frontend/src
sonar.exclusions=**/node_modules/**,**/build/**,**/coverage/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
